name: flutter_clean_domain
description: A plugin that provides core elements for implementing the domain layer of a Clean Architecture app
version: 1.0.0

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.0

  # Functional programming
  dartz: ^0.10.0-nullsafety.2

dev_dependencies:
  # Linting and Code analysis
  effective_dart: 1.3.1

