name: Check PR title is conventional
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - converted_to_draft

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: aslafy-z/conventional-pr-title-action@v2.2.5
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}